### ISSUE TITLE
suggestion: keypress sound

### ISSUE THREAD

**Issue by beanlee** [cssmagic/Oh-My-MacDown#1]
What a Wonderfull tool !
Can It Increased the keypress sound like a Typewriter? 
You know my Mechanical keyboard is in the office : )

**Comment by cssmagic** [comment]
发现 Mou 是有按键音功能的呢！虽然我从来没用过，呵呵。

不过很抱歉我帮不到你。你可以向 MacDown 的作者 [提功能建议](https://github.com/uranusjr/macdown/issues)，也可以试试 [Mac 自带的全局按键音](http://bbs.feng.com/read-htm-tid-3869349.html)。

**Comment by beanlee** [comment]
谢谢你的回复，还帮我找到另外的解决办法 : )
