### ISSUE TITLE
这个怎么用？

### ISSUE THREAD

**Issue by wozzup** [cssmagic/Oh-My-MacDown#2]
请问这个 theme 怎么用？
请问作者达人有没有办法给 macdown 做一个自己的模版？比如，在 toc 里增一个嵌套？需要自己编译吗？

**Comment by cssmagic** [comment]
> 请问这个 theme 怎么用？
1. 手动将 `Zen Dark.css` 和 `Zen Dark.style` 文件分别复制到 `~/Library/Application Support/MacDown` 下的 `Styles` 和 `Themes` 目录，或者创建软连接。
2. 重新启动 MacDown。

**Comment by cssmagic** [comment]
> 请问作者达人有没有办法给 macdown 做一个自己的模版？比如，在 toc 里增一个嵌套？需要自己编译吗？

抱歉，我没有能力修改 MacDown 的渲染行为。如果你有需求，可以 [向 MacDown 项目提 issue](https://github.com/uranusjr/macdown/issues)。 :smiley:

**Comment by wozzup** [comment]
好的，多谢啦 :)
